#In SSMS, use localhost,1433 as server name...

version: "3"
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "${DB_PW}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  
  commander-api:
    container_name: commander-api
    image: mrgruby/cleancommander-api:latest
    build:
      context: .
      dockerfile: CleanCommander.Api/dockerfile
    ports:
      - "8080:80"
    depends_on:
      - ms-sql-server
    environment:
      DB_PW:
volumes:
  mssql-server-data: